DROP TABLE  R;
DROP TABLE  S;
CREATE TABLE R (A INT, B VARCHAR(64), C INT, D INT, 
CONSTRAINT CR1 PRIMARY KEY (A, C), 
CONSTRAINT CR2 CHECK (LENGTH(B) IN (3,4,6,7)),  
CONSTRAINT CR3 CHECK (D IN (1,2,4,8,16,32,64,128,256)),  
CONSTRAINT CR4 UNIQUE (D)  
);  
CREATE TABLE S (A INT, B INT, C INT, D INT, E INT, 
CONSTRAINT CS1 PRIMARY KEY (A,E), 
CONSTRAINT CS2 FOREIGN KEY (E) REFERENCES R(D),  
CONSTRAINT CS3 CHECK (D BETWEEN 12 AND 16)  
);  